//指定proto3版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家的输入操作 (客户端 -> 服务端)
// 每帧发送 因为按的频率很高
type PlayerInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 左右移动输入(-1.0 到 1.0,Unity中的定义，-1为最左，1为最右), 对应Unity的Input.GetAxis("Horizontal")
	MoveX float32 `protobuf:"fixed32,1,opt,name=move_x,json=moveX,proto3" json:"move_x,omitempty"`
	// 同上，表上下移动(-1.0 到 1.0), 对应Unity的Input.GetAxis("Vertical")
	MoveY float32 `protobuf:"fixed32,2,opt,name=move_y,json=moveY,proto3" json:"move_y,omitempty"`
	// 玩家鼠标朝向的角度(0 - 360度)，用于让角色面朝鼠标
	ViewAngle float32 `protobuf:"fixed32,3,opt,name=view_angle,json=viewAngle,proto3" json:"view_angle,omitempty"`
	// 是否按下了开火键(true/false)
	Fire bool `protobuf:"varint,4,opt,name=fire,proto3" json:"fire,omitempty"`
	// 客户端发送时的毫秒时间戳 (用于计算延迟 Ping 值)
	Time          int64 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInput) GetMoveX() float32 {
	if x != nil {
		return x.MoveX
	}
	return 0
}

func (x *PlayerInput) GetMoveY() float32 {
	if x != nil {
		return x.MoveY
	}
	return 0
}

func (x *PlayerInput) GetViewAngle() float32 {
	if x != nil {
		return x.ViewAngle
	}
	return 0
}

func (x *PlayerInput) GetFire() bool {
	if x != nil {
		return x.Fire
	}
	return false
}

func (x *PlayerInput) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 单个玩家数据
type PlayerState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 玩家ID 唯一
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 当前位置 x
	PosX float32 `protobuf:"fixed32,2,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	// 当前位置 y
	PosY float32 `protobuf:"fixed32,3,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	// 当前朝向角度
	Rotation float32 `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	// 当前生命值
	Hp            int32 `protobuf:"varint,5,opt,name=hp,proto3" json:"hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerState) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerState) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *PlayerState) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *PlayerState) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *PlayerState) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

// 世界状态 (服务端 -> 客户端)
type WorldState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "repeated"关键字表示这是一个列表(List/Array)
	// 当局所有玩家状态（嵌套）
	Players []*PlayerState `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	// 服务端当前的逻辑帧时间 (用于客户端做插值同步)
	ServerTime    int64 `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldState) Reset() {
	*x = WorldState{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldState) ProtoMessage() {}

func (x *WorldState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldState.ProtoReflect.Descriptor instead.
func (*WorldState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *WorldState) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *WorldState) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 登录请求 (客户端 -> 服务端)
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 玩家名字
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 登录响应 (服务端 -> 客户端)
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 玩家ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 是否让进（密码/网络）
	Success       bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x02pb\"\x82\x01\n" +
	"\vPlayerInput\x12\x15\n" +
	"\x06move_x\x18\x01 \x01(\x02R\x05moveX\x12\x15\n" +
	"\x06move_y\x18\x02 \x01(\x02R\x05moveY\x12\x1d\n" +
	"\n" +
	"view_angle\x18\x03 \x01(\x02R\tviewAngle\x12\x12\n" +
	"\x04fire\x18\x04 \x01(\bR\x04fire\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x03R\x04time\"s\n" +
	"\vPlayerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x13\n" +
	"\x05pos_x\x18\x02 \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x03 \x01(\x02R\x04posY\x12\x1a\n" +
	"\brotation\x18\x04 \x01(\x02R\brotation\x12\x0e\n" +
	"\x02hp\x18\x05 \x01(\x05R\x02hp\"X\n" +
	"\n" +
	"WorldState\x12)\n" +
	"\aplayers\x18\x01 \x03(\v2\x0f.pb.PlayerStateR\aplayers\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"\"\n" +
	"\fLoginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\rLoginResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccessB\x17Z\x05./;pb\xaa\x02\rGame.Protocolb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_game_proto_goTypes = []any{
	(*PlayerInput)(nil),   // 0: pb.PlayerInput
	(*PlayerState)(nil),   // 1: pb.PlayerState
	(*WorldState)(nil),    // 2: pb.WorldState
	(*LoginRequest)(nil),  // 3: pb.LoginRequest
	(*LoginResponse)(nil), // 4: pb.LoginResponse
}
var file_game_proto_depIdxs = []int32{
	1, // 0: pb.WorldState.players:type_name -> pb.PlayerState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
